jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Speedlogger Docker image
      run: docker build ./docker_speedlogger --file ./docker_speedlogger/Dockerfile --tag speed-logger:$(date +%s)
    - name: Build the Pinglogger Docker image
      run: docker build ./docker_pinglogger --file ./docker_pinglogger/Dockerfile --tag ping-logger:$(date +%s)